### PR TITLE
fix mispell

### PR DESCRIPTION
**Pull request by chemidy**

### CODE REVIEW

**Comment by zagrodzki** [comment]
It seems our build script is not working properly anymore, I'll fix that next week. Sorry for the delay.

**Comment by chemidy** [comment]
Yes Seems golint is no longer supported for go 1.7 and 1.8

**Comment by zagrodzki** [comment]
No, sorry, I got confused, that's not lint that was merged. I think you're saying that go 1.7/1.8 are not supported, but the linter works with 1.9 and above. We'll need to update the go versions, 1.7 is over 2y old, so I think we can drop it. 1.8 is not 2y old yet, so I'd prefer to keep it and just check the version in the build script, skip lint if not 1.9 or above.

**Comment by zagrodzki** [comment]
Thanks for all the fixes!

**Pull request merged**
