### PR TITLE
ADD: GetDescriptor

### PR DESCRIPTION
**Pull request by NullYing**
use example:

https://github.com/OpenPrinting/ipp-usb/blob/2aa0ad4bdca06b1a9071d109da09e831e2f6d42b/usbio_libusb.go#L529

### CODE REVIEW

**Comment by zagrodzki** [comment]
would this functionality perhaps be satisfied by the `ExtraDescriptors` proposed in https://github.com/google/gousb/pull/127? I don't really want to add thin wrappers around libusb functionality in the code. My understanding is that IPP class descriptor is essentially an additional descriptor attached to the USB interface descriptor, something that libusb represents as "extra" part of the interface (see https://libusb.sourceforge.io/api-1.0/structlibusb__interface__descriptor.html). If that could work, then I prefer that approach over wrapping lower level libusb functions.

**Comment by NullYing** [comment]
I don't know which data I need from ExtraDescriptors. By encapsulating `libusb_get_descriptor`, I can clearly know that I need to get the data at position 0x21. Moreover, during USB communication, only the `get_descriptor` instruction at position 0x21 is sent. I believe `GetStringDescriptor` and `GetDescriptor` are interfaces of the same level. Whether to fetch all the ExtraDescriptors in one go should be left to the user's choice.

**Comment by zagrodzki** [comment]
any thoughts? I'll be publishing a new release in ~2wks, it would be nice if we included support for the extra descriptors. If you agree with what I wrote, the best option would be to follow up on PR #127, which should satisfy your needs, but which needs some work before it can go in.

**Comment by NullYing** [comment]
No,thanks.I will focus on the new release

**Pull request closed without merging**
